### ISSUE TITLE
Can't understand the error probably due to wrong config parameter

### ISSUE THREAD

**Issue by invasionofsmallcubes** [ShopRunner/apparate#22]
Hi guys, 
I'm getting an incomprensible error from apparate:

```
new library rcm-datalogs-consumer_2.11-0.1.0 loaded to Databricks
Traceback (most recent call last):
  File "/usr/local/bin/apparate", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/apparate/cli_commands.py", line 135, in upload_and_update
    cleanup=cleanup
  File "/usr/local/lib/python3.7/site-packages/apparate/update_databricks_library.py", line 528, in update_databricks
    host,
  File "/usr/local/lib/python3.7/site-packages/apparate/update_databricks_library.py", line 279, in get_library_mapping
    library_list = res.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/local/lib/python3.7/site-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/local/lib/python3.7/site-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

can you suggest a way to investigate on this? I have no idea of what I'm doing wrong.

**Comment by invasionofsmallcubes** [comment]
I've just notice this fine print
```Note: apparate requires python3, and currently only works on Databricks accounts that run AWS (not Azure)```
